export const ADD_NEW_TODO = "TODOS/ADD_NEW_TODO";
export const REMOVE_TODO = "TODOS/REMOVE_TODO";
export const TOOGLE_TODO = "TODOS/TOOGLE_TODO";
export const TOOGLE_ALL_TODO = "TODOS/TOOGLE_ALL_TODO";
export const START_EDITING_TODO = "TODOS/START_EDITING_TODO"
export const END_EDITING_TODO = "TODOS/END_EDITING_TODO"
export const CLEAR_COMPLETED_TODO = "TODOS/CLEAR_COMPLETED_TODO"
export const SET_WINDOW_LOCATION = "ROUTER/SET_WINDOW_LOCATION"


